my_speed:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT', 'iron-figure-312018') }}"
      dataset: "{{ env_var('BQ_MARTS', 'speed_marts') }}"
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      keyfile: /opt/airflow/credentials/sa-key.json
      threads: 4
      priority: interactive
    local:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT', 'iron-figure-312018') }}"
      dataset: "{{ env_var('BQ_MARTS', 'speed_marts') }}"
      location: "{{ env_var('BQ_LOCATION', 'US') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
